/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings worker/env.d.ts` (hash: 1061e4ce7b9990470d620eaa9cb9ad0e)
interface __BaseEnv_WorkerBindings {
	APP_ORIGIN: string;
	TWITCH_CLIENT_ID: string;
	TWITCH_CLIENT_SECRET: string;
	STEAM_WEB_API_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	AUTH: DurableObjectNamespace<import("./index").IntegrationState>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "IntegrationState";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "TWITCH_CLIENT_ID" | "TWITCH_CLIENT_SECRET" | "STEAM_WEB_API_KEY" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
